### ISSUE TITLE
Stat_models example

### ISSUE THREAD

**Issue by m6129** [lss-1138/SparseTSF#2]
Dear Developer. Let me thank you for your work.
Very interesting approach.

I noticed that you have [Stat_models](https://github.com/lss-1138/SparseTSF/blob/main/models/Stat_models.py) figuring in both model repositories (SegRNN, SparseTSF), while you do not experiment in articles with this code. You have an example script with an implementation of how the models work from the [Stat_modelss file](https://github.com/lss-1138/SparseTSF/blob/main/models/Stat_models.py) ?

**Comment by lss-1138** [comment]
Thank you for your interest. Indeed, we currently do not have examples utilizing Stat models. This is because traditional models have been proven inadequate for long sequence forecasting tasks. If you're looking for an example script on how to use these Stat models, you can refer to [**LTSF-Linear**](https://github.com/cure-lab/LTSF-Linear). Inside, you'll find essential files such as **run_stat.py**, **exp/exp_stat.py**, and scripts like **EXP-LongForecasting/Stat_Long.sh** that demonstrate their usage.

**Comment by m6129** [comment]
**thank you very much**

**Comment by m6129** [comment]
I would like to say that the method "closest repeat 96", obtained impressive results, for such a naive forecasting method

**Comment by lss-1138** [comment]
Yes. In fact, the current practical foundation for achieving long-term forecasts lies in the long-term dependencies hidden within the data, or in other words, periodicity. For datasets with relatively weaker periodicity, such as financial datasets or ETT datasets, the 'closest repeat 96' method has already achieved good numerical results. Achieving accurate predictions for these datasets is still quite challenging at present.
